name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: cloudflare/wrangler-action@2.0.0
        name: Deploy to Cloudflare (Production)
        with:
          apiToken: '${{ secrets.CF_API_TOKEN }}'
          environment: 'production'
          secrets: |
            DATABASE_URL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
